-- Run this in a Snowsight SQL worksheet after you have a student trial.
-- Warehouse: X-Small is enough. Do not paste a PAT here.

CREATE WAREHOUSE IF NOT EXISTS SEE_THROUGH_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS SEE_THROUGH;
CREATE SCHEMA IF NOT EXISTS SEE_THROUGH.APP;

USE WAREHOUSE SEE_THROUGH_WH;
USE DATABASE SEE_THROUGH;
USE SCHEMA APP;

CREATE TABLE IF NOT EXISTS SCENE_EVENTS (
  EVENT_ID NUMBER AUTOINCREMENT,
  TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  MATCHED BOOLEAN,
  PERSON_NAME STRING,
  RELATIONSHIP STRING,
  SCORE FLOAT,
  OBSTACLES VARIANT,
  PLACE STRING,
  SUMMARY_TEXT STRING
);

-- inside_safe_zone is derived from PLACE (home=true, away=false) and stored
-- in SUMMARY_TEXT. Phone GPS / a lat-lng geofence can replace PLACE later.

-- Optional event index. Skip this if CREATE CORTEX SEARCH SERVICE is not
-- allowed on your trial; routine reminders still use recent event rows.
CREATE OR REPLACE CORTEX SEARCH SERVICE SCENE_SEARCH
  ON SUMMARY_TEXT
  ATTRIBUTES PLACE, PERSON_NAME, MATCHED
  WAREHOUSE = SEE_THROUGH_WH
  TARGET_LAG = '1 minute'
  AS (
    SELECT
      SUMMARY_TEXT,
      PLACE,
      PERSON_NAME,
      MATCHED,
      TS
    FROM SCENE_EVENTS
    WHERE SUMMARY_TEXT IS NOT NULL
  );

-- Confirm Cortex SQL complete works even if REST is trial-blocked:
-- SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3.1-8b', 'Say hi in 5 words');
